name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        day: [ day01, day02, day03, day04, day05, day06, day07 ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build test_${{matrix.day}}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig fmt --check day*/*.zig
